services:
  php:
    build:
      context: .
      dockerfile: docker/PHP.DockerFile
    volumes:
      - ./:/app
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: